### ISSUE TITLE
iscsi命令，LUN map问题

### ISSUE THREAD

**Issue by kevinwd** [FeixiDev/Orion#18]
**Describe the bug**
使用iscsi命令，将LUN映射给host时，出现以下报错：

root@node40:/home/horatio# ./vtel_client_main iscsi map c lun_node21 -hg only_node21 -dg all_lun         
Create iSCSILogicalUnit success
set coclocation success
set order success
create colocation and order success:apple
Failde to create resource!
root@node40:/home/horatio# 

![Screen Shot 2020-10-16 at 3 40 08 PM](https://user-images.githubusercontent.com/29305054/96228034-96edaf80-0fc7-11eb-88de-6ed2e464fa94.png)

建议：经测试，可能是LUN id获取的逻辑问题

Frederic Wu

**Comment by klaylin** [comment]
![image](https://user-images.githubusercontent.com/42958736/96228502-3f9c0f00-0fc8-11eb-97e9-2895cfcc9886.png)
资源报错是因为iSCSI LUN LUN ID以“0”开头，targetcli无法配置
LUN ID目前获取机制为获取DRBD资源设备名的后两位，如/dev/drbd1000获取的LUN ID为00，建议LUN ID获取机制可以试试改成设备名/dev/drbd之后的数字减去1000
