### ISSUE TITLE
diskgroup创建失败问题

### ISSUE THREAD

**Issue by Zhgx** [FeixiDev/Orion#36]
1.执行‘python3 vtel_client_main.py iscsi dg c dg_sptest_test sptest’时报错
Fail! Can't find sptest.Please give the true name.

2.执行‘python3 vtel_client_main.py iscsi d s ’查看可获取环境resource

3.执行‘python3 vtel_client_main.py iscsi dg c dg_sptest_test sptest’
Create success!

需通过执行‘python3 vtel_client_main.py iscsi d s ’将环境最新数据更新到json文件中，才能创建。

**Comment by userhei** [comment]
将环境最新数据更新到json文件中，才能创建？
--》这个说法应该不准确吧？具体情况Zane早会可以详细描述下。
