### ISSUE TITLE
部分功能的help显示的usage有误

### ISSUE THREAD

**Issue by MissRrr** [FeixiDev/Orion#64]
**Describe the bug**
host的show功能的help显示有误，usage显示的是modify的内容；diskgroup的create功能help显示有误，usage显示的是整个hg的usage的内容。

**Screenshots**
root@ubuntu:/VersaTEL-dev/Orion/vplx# python3 vtel.py iscsi h s -h
usage: 
    host(h) modify(m) HOST IQN

root@ubuntu:/VersaTEL-dev/Orion/vplx# python3 vtel.py iscsi dg c -h
usage: diskgroup(dg) {create(c)/modify(m)/delete(d)/show(s)} create
       [-h] diskgroup disk [disk ...]

**Comment by mattie-feng** [comment]
补充usage的其他两个问题：
```root@ubuntu:/home/samba/mattie/O/Orion/vplx# python3 vtel.py stor -h
usage: vtel [-h] [-v]  ...
vtel: error: unrecognized arguments: -h
```
```
root@ubuntu:/home/samba/mattie/m/Orion/vplx# python3 vtel.py iscsi -h
usage: vtel [-h] [-v]  ...
vtel: error: unrecognized arguments: -h
```
