### ISSUE TITLE
diskgroup和hostgroup删除函数的检查分支有误

### ISSUE THREAD

**Issue by MissRrr** [FeixiDev/Orion#65]
**Describe the bug**
delete_diskgroup和delete_hostgroup删除已经配置在map的diskgroup和hostgroup能直接成功删除，但map结构仍会存在。应该不能直接删除，而是要先删除配置了该diskgroup或hostgroup的map，再对该diskgroup或hostgroup进行删除。需要修改iscsi_json模块的check_value函数。

**To Reproduce**
1. 创建新的diskgroup和hostgroup
2. 创建新的map，将刚刚创建的diskgroup和hostgroup配置在map下
3. 删除刚刚已经配置在map中diskgroup或hostgroup
4. 错误结果：该diskgroup或hostgroup删除成功  正确结果：提示Fail! The hostgroup/diskgroup already map,Please delete the map

**Expected behavior**
正确结果：提示Fail! The hostgroup/diskgroup already map,Please delete the map，而且该diskgroup或hostgroup不能删除成功

**Comment by mattie-feng** [comment]
业务逻辑已修改：删除HostGroup或者DiskGroup前，都会提示删除该组会受到影响，等待用户确认删除之后才会去执行删除操作。
