### ISSUE TITLE
创建 portal：调整底层 crm order 顺序

### ISSUE THREAD

**Issue by tian-fxt** [FeixiDev/Orion#91]
**Describe the bug**
创建 portal 使用的 crm 配置命令中，创建 vip 与 portblock_on 的 order 关系目前使用的是以下命令：
`crm cof order <order_name> <vip_name> <prtblk_block_name>`
表示 vip 在 portblock(block) 之前启动。
经 LINBIT 指出，这里逻辑存在问题，应该是 portblock(block) 在 vip 之前启动。
**Expected behavior**
将这条order 命令改成：
`crm cof order <order_name> <prtblk_block_name> <vip_name>`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: None
 - Version: Orion v1.0.0-RC

**Additional context**
portblock 的 block/unblock 是去避免 initiators 看到没有完全配置的 iSCSI。目前我的理解是，在故障转移场景下，initiators 也会一直使用这个 IP 地址去尝试访问， 所以 portblock 的 block 如果在 vip 之前被关闭、在 vip 之后被开启，vip 存在暴露的风险；因此要设置 portblock 的 block 在 vip 之前启动（同样，关闭时 portblock 在 vip 之后关闭），以避免 initiator 访问到没有配置 iSCSI target 的 vip 地址。

**Comment by mattie-feng** [comment]
已完成修改，之后提交的代码会有这部分的更新。该Issue关闭。
